### ISSUE TITLE
Required property "XUID"

### ISSUE THREAD

**Issue by frizib** [mhsjlw/pocket-minecraft-protocol#200]
Hello!
When connecting bots, this error occurs in the server console and the bot does not log in.

I form the client like this:

```
    const client = bedrock.createClient({
        host: host,
        port: port,
        username: nick,
        offline: true,
        authTitle: bedrock.title.MinecraftNintendoSwitch

    })
```

**The main condition is authorization to pirate servers without using an xbox account**

Error:
### [15:22:25.234] [Server thread/ERROR]: [NetworkSession: 45.142.122.165 58593] Bad packet (error ID 9acd0523567d): Error processing LoginPacket: Required property "XUID" of class pocketmine\network\mcpe\protocol\types\login\AuthenticationData is missing in JSON data

**Comment by frizib** [comment]
[log.txt](https://github.com/PrismarineJS/bedrock-protocol/files/8546853/log.txt)

debug

**Comment by extremeheat** [comment]
Sign in online if you want to login as an Xbox user

**Comment by frizib** [comment]
> Sign in online if you want to login as an Xbox user

I told you I don't need an xbox

**Comment by frizib** [comment]
Without an xbox account, you can no longer use bots?

**Comment by extremeheat** [comment]
Yes, if the server supports offline accounts. It works fine on vanilla servers (BDS), it's possible PocketMine doesn't allow non-xbox users to connect. Try a different server software or if you think there's something we can do here to fix this feel free to propose solutions

**Comment by extremeheat** [comment]
Is your PM server running in offline mode? If it is I notice we don't send a XUID at all in offline mode. Maybe we could default it to 0.

**Comment by frizib** [comment]
The server has the ability to accept players without a hbox account. Also, I just logged into the server without authorization.

server.properties:
`xbox-auth=off`

Also in the kernel settings I found the setting:
Here, too, you can see that the server does not require verification of the XUID
```
player:
  #Choose whether to enable player data saving.
  save-player-data: true
  #If true, checks that joining players' Xbox user ID (XUID) match what was previously recorded.
  #This also prevents non-XBL players using XBL players' usernames to steal their data on servers with xbox-auth=off.
  verify-xuid: false
  
```
